name: publish

on: 
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needs to push tags
    if: startsWith(github.head_ref, 'releases/v') && github.event.pull_request.merged == true
    env:
      REPO: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Initialize
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Get tag name
        id: vars
        run: |
          HEAD_REF=${{ github.head_ref }}
          echo "tag=${HEAD_REF##*/v}" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Push Tag
        run: |
          git tag -a v${{ steps.vars.outputs.tag }} -m "Release ${{ steps.vars.outputs.tag }}"
          git push $REPO v${{ steps.vars.outputs.tag }}

      - uses: goreleaser/goreleaser-action@v4
        with:
            args: release --clean
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動で生成されるシークレット
            TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
